const fs=require('fs'),vm=require('vm'),assert=require('assert');const els=new Map(),noop=()=>{},ctx=new Proxy({createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop})},{get:(o,k)=>o[k]||noop});const box={document:{addEventListener(){},querySelector(s){if(!els.has(s))els.set(s,{style:{},setAttribute(){},addEventListener(){},getContext(){return ctx}});return els.get(s)}},innerWidth:1000,innerHeight:900,devicePixelRatio:1,addEventListener(){},requestAnimationFrame(){},localStorage:{},console,assert};vm.createContext(box);vm.runInContext(fs.readFileSync('index.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1],box);
vm.runInContext(`function step(dt){if(state==='playing'&&waitingForMove)rotate(.000001);update(dt)}start();assert(completed.every(x=>!x));let frames=0;while(state==='playing'&&frames++<10000){let p=platforms.find(p=>!p.broken);if(p)angle=mod(Math.PI/2-p.start);step(1/60);if(frames%30===0)draw()}assert.equal(state,'won');assert(completed[0]);assert($('#dots').innerHTML.includes('#ff5670'));step(2);assert.equal(level,0);assert.equal(state,'won');$('#next').onclick();assert.equal(level,1);assert.equal(platforms.length,20);assert.equal(state,'playing');assert(platforms.every(p=>p.hazard===.38));assert.equal(passed,0);
// Land in the centre of either black tip; restart must preserve red completion.
for(let side of [-1,1]){let p=platforms[0];angle=mod(Math.PI/2-p.start-side*(p.width/2+p.hazard/2));ballY=p.y-1;vy=100;step(.02);assert.equal(state,'dying');draw();for(let i=0;i<60;i++)step(1/60);assert.equal(state,'playing');assert.equal(level,1);assert(completed[0]);assert.equal(passed,0)}
// Gap is safe; ordinary orange contact bounces.
let p=platforms[0];angle=mod(Math.PI/2-p.start);assert(gap(p)&&!danger(p));angle=0;ballY=-1;vy=100;step(.02);assert(vy<0&&state==='playing');
// Complete orange by bouncing on each floor before aligning the gap.
restartLevel();let bounced=new Set(),lastPass=0;frames=0;while(state==='playing'&&frames++<30000){let p=platforms.find(p=>!p.broken);if(p&&bounced.has(p))angle=mod(Math.PI/2-p.start);let previousVy=vy;step(1/60);if(previousVy>0&&vy<0&&p)bounced.add(p);if(frames%30===0)draw();assert(Math.abs(ballY-camera-100)<1e-8)}assert.equal(state,'won');assert.equal(passed,20);assert.equal(bounced.size,20);assert(completed[0]&&completed[1]);assert($('#dots').innerHTML.includes('#ffa34f'));

$('#next').onclick();assert.equal(level,2);assert.equal(platforms.length,20);assert.equal(new Set(platforms.map(p=>p.splits)).size,3);
// Every yellow opening remains usable; all painted areas match lethal collisions.
for(let floor=0;floor<20;floor++){
restartLevel();let p=platforms[floor];assert(blackZones(p).length<=2);assert.equal(p.tip>=0,floor%2===1);
for(let k=0;k<p.splits;k++){restartLevel();p=platforms[floor];angle=mod(Math.PI/2-p.start-k*TAU/p.splits);assert(gap(p)&&!danger(p));ballY=p.y-1;vy=200;step(.04);assert(p.broken&&state==='playing');draw()}
restartLevel();p=platforms[floor];for(let [lo,hi] of blackZones(p)){restartLevel();p=platforms[floor];angle=mod(Math.PI/2-(lo+hi)/2);ballY=p.y-1;vy=100;step(.02);assert.equal(state,'dying');draw();step(1);assert.equal(level,2);assert(completed[0]&&completed[1])}
// Each platform keeps at least one completely safe tip to land on.
restartLevel();p=platforms[floor];let safe=spans(p).flatMap(([lo,hi])=>[lo+.1,hi-.1]).filter(q=>!blackAt(p,q));assert(safe.length>=p.splits*2-1);angle=mod(Math.PI/2-safe[0]);ballY=p.y-1;vy=100;step(.02);assert.equal(state,'playing');assert(vy<0);draw();
}
// Complete yellow through a mix of its available routes.
restartLevel();frames=0;while(state==='playing'&&frames++<10000){let p=platforms.find(p=>!p.broken);if(p)angle=mod(Math.PI/2-p.start-(passed%p.splits)*TAU/p.splits);step(1/60);if(frames%30===0)draw();assert(Math.abs(ballY-camera-100)<1e-8)}assert.equal(state,'won');assert.equal(passed,20);assert(completed.slice(0,3).every(Boolean));assert($('#dots').innerHTML.includes('#ffe06c'));assert.equal($('#bar').style.width,'100%');console.log('PASS: mixed yellow gaps, sparse hazards, safe tips, all three stages and render calls.');`,box);
// Saved unlocks and per-level records survive fresh page contexts.
const code=fs.readFileSync('index.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
const reloadBox={...box,localStorage:{...box.localStorage}};vm.createContext(reloadBox);vm.runInContext(code,reloadBox);vm.runInContext("function step(dt){if(state==='playing'&&waitingForMove)rotate(.000001);update(dt)}",reloadBox);
vm.runInContext(`assert(completed.slice(0,3).every(Boolean));assert(bestTimes.slice(0,3).every(t=>t>0));selectLevel(1);assert.equal(level,1);assert(solo);assert.equal(levelTime,0);let oldTime=bestTimes[1];levelTime=oldTime+5;finish();assert.equal(bestTimes[1],oldTime);levelTime=oldTime/2;finish();assert(bestTimes[1]<oldTime);restartLevel();let frozenY=ballY;openPicker();step(.5);assert.equal(levelTime,0);assert.equal(ballY,frozenY);assert.equal(state,'picker');closePicker();assert.equal(state,'playing');assert(completed[0]);let keptLevel=level;selectLevel(4);assert.equal(level,keptLevel);`,reloadBox);
const freshBox={...box,localStorage:{}};vm.createContext(freshBox);vm.runInContext(code,freshBox);vm.runInContext("function step(dt){if(state==='playing'&&waitingForMove)rotate(.000001);update(dt)}",freshBox);
vm.runInContext(`assert(unlocked(0));assert(!unlocked(1)&&!unlocked(2)&&!unlocked(3));openPicker();selectLevel(2);assert.equal(state,'picker');assert.equal(level,0);selectLevel(0);assert.equal(state,'playing');levelTime=10;finish();assert(completed[0]);assert(unlocked(1)&&!unlocked(2));selectLevel(1);assert.equal(levelTime,0);assert.equal(level,1);levelTime=2;die();step(1);assert.equal(level,1);assert.equal(levelTime,0);assert(completed[0]);assert.equal(bestTimes[1],null);`,freshBox);
console.log('PASS: saved unlocks and records, locked-level guards, replay best times, paused picker, death/restart timing.');
// Green unlocks from yellow and stops large drags at blockers in either direction.
vm.runInContext(`assert.equal(level,2);assert.equal(state,'won');nextLevel();assert.equal(level,3);assert.equal(platforms.length,10);assert(platforms.every(p=>p.wall!==null));assert.equal(unlocked(4),false);
for(let floor=0;floor<10;floor++){
restartLevel();for(let i=0;i<floor;i++)platforms[i].broken=true;passed=floor;let p=platforms[floor],side=floor%2?-1:1;ballY=p.y;camera=ballY-100;vy=-265;angle=mod(Math.PI/2-p.start-side*1.5);rotate(side*TAU*2);let atStop=angle;assert(blockFlash>0);assert(Math.abs(Math.abs(Math.atan2(Math.sin(angle+p.wall-Math.PI/2),Math.cos(angle+p.wall-Math.PI/2)))-.25)<1e-8);rotate(side*TAU);assert(Math.abs(angle-atStop)<1e-8);rotate(-side*.15);assert(Math.abs(angle-atStop)>.1);
let n=0;while(!p.broken&&state==='playing'&&n++<1000){if(!gap(p))rotate(-side*3.5/60);step(1/60);if(n%10===0)draw()}assert.equal(state,'playing');assert(p.broken,'Alternate route must clear floor '+floor);assert.equal(passed,floor+1);
}
// Full green run through physics and incremental rotation, with no angle teleporting.
restartLevel();let steps=0;while(state==='playing'&&steps++<20000){let p=platforms.find(p=>!p.broken);if(p){let i=platforms.indexOf(p),side=i%2?-1:1;if(!gap(p))rotate(-side*3.5/60)}step(1/60);if(steps%30===0)draw()}assert.equal(state,'won');assert.equal(passed,10);assert(completed[3]);assert(bestTimes[3]>0);assert(unlocked(4));nextLevel();assert.equal(level,4);assert.equal(platforms.length,10);`,box);
console.log('PASS: Next Level transitions, green unlock, both blocker directions, large-drag clamping, all 10 alternate routes and full green completion.');

// Blue keeps the blockers and adds spaced, wider floor strips that can be jumped over.
vm.runInContext(`assert.equal(level,4);assert.equal(platforms.length,10);assert(platforms.every(p=>p.lines===3||p.lines===4));assert.equal(unlocked(5),false);
for(let floor=0;floor<10;floor++){
restartLevel();let p=platforms[floor],zones=blackZones(p);assert.equal(zones.length,p.lines);
for(let [a,b] of zones){assert(Math.abs(b-a-.36)<1e-8);restartLevel();p=platforms[floor];angle=mod(Math.PI/2-(a+b)/2);assert(!gap(p)&&danger(p));ballY=p.y-1;vy=100;step(.02);assert.equal(state,'dying');draw();step(1);assert.equal(level,4);assert(completed[3]);
// Travel across the same strip during a bounce without touching its surface.
restartLevel();p=platforms[floor];angle=mod(Math.PI/2-a+.03);ballY=p.y-30;vy=-100;rotate(-(b-a+.06));step(.02);assert.equal(state,'playing');assert(vy<0);draw();}
}
// Complete blue with a separate timed bounce over each strip, using normal rotation speed.
restartLevel();let ticks=0,target=null,targetPlatform=null,blueBounces=0;
while(state==='playing'&&ticks++<30000){let p=platforms.find(p=>!p.broken);if(p!==targetPlatform){target=null;targetPlatform=p}if(p&&target!==null){let q=mod(p.wallSide*(Math.PI/2-angle-p.start)),remaining=target-q;let step=Math.min(3.5/60,Math.max(0,remaining));rotate(-p.wallSide*step);if(remaining<=3.5/60+.00001)target=null}let oldVy=vy;step(1/60);if(oldVy>0&&vy<0&&p){blueBounces++;let q=mod(p.wallSide*(Math.PI/2-angle-p.start)),stops=Array.from({length:p.lines},(_,j)=>2.42+j*2.8/(p.lines-1));stops.push(TAU);target=stops.find(t=>t>q+.04)??null;}if(ticks%30===0)draw()}
assert.equal(state,'won');assert.equal(passed,10);assert(completed[4]);assert(bestTimes[4]>0);assert(blueBounces>=30);assert(unlocked(5));nextLevel();assert.equal(level,5);assert.equal(platforms.length,56);`,box);
console.log('PASS: 3–4 blue strips per floor, lethal landings, safe airborne crossings, blue-only reset and full timed-bounce completion.');

// Indigo alternates three bounce floors and 25 deadly drop floors, twice.
vm.runInContext(`assert.equal(level,5);assert.equal(platforms.length,56);assert.equal(platforms.filter(p=>p.lethal).length,50);assert.equal(platforms.filter(p=>p.wall!==null).length,6);
for(let floor=0;floor<56;floor++){let p=platforms[floor];assert.equal(p.lethal,floor%28>=3);if(!p.lethal)continue;let [lo,hi]=spans(p)[0];for(let q of [lo+.03,(lo+hi)/2,hi-.03]){restartLevel();p=platforms[floor];angle=mod(Math.PI/2-q);ballY=p.y-1;vy=100;step(.02);assert.equal(state,'dying');draw();step(1);assert.equal(level,5);assert(completed[4])}restartLevel();p=platforms[floor];angle=mod(Math.PI/2-p.start);assert(gap(p)&&!danger(p));ballY=p.y-1;vy=200;step(.04);assert(p.broken&&state==='playing');}
// Gaps turn exactly 360 degrees from first to last drop floor, at 15 degrees per step.
for(let first of [3,31]){let turn=0;for(let j=1;j<25;j++){let d=mod(platforms[first+j].start-platforms[first+j-1].start);assert(Math.abs(d-TAU/24)<1e-8);turn+=d}assert(Math.abs(turn-TAU)<1e-8)}
for(let p of platforms.filter(p=>!p.lethal))for(let [a,b] of blackZones(p))assert(Math.abs(b-a-.54)<1e-8);
// Each long-drop section can be descended continuously with gentle steering.
for(let first of [3,31]){restartLevel();for(let i=0;i<first;i++)platforms[i].broken=true;passed=first;ballY=platforms[first].y-40;vy=420;angle=mod(Math.PI/2-platforms[first].start);let n=0;while(!platforms[first+24].broken&&n++<1000){let p=platforms.find(p=>!p.broken);let d=Math.atan2(Math.sin(Math.PI/2-p.start-angle),Math.cos(Math.PI/2-p.start-angle));rotate(Math.max(-3.5/60,Math.min(3.5/60,d)));step(1/60);assert.equal(state,'playing');assert(vy>0);if(n%10===0)draw()}assert(platforms[first+24].broken)}
// Play the entire course with bounce-timed strip crossings and smooth gap steering.
restartLevel();let frameCount=0,goal=null,courseFloor=null;while(state==='playing'&&frameCount++<30000){let p=platforms.find(p=>!p.broken);if(p!==courseFloor){goal=null;courseFloor=p}if(p?.lethal){let d=Math.atan2(Math.sin(Math.PI/2-p.start-angle),Math.cos(Math.PI/2-p.start-angle));rotate(Math.max(-3.5/60,Math.min(3.5/60,d)))}else if(p&&goal!==null){let q=mod(p.wallSide*(Math.PI/2-angle-p.start)),remaining=goal-q;rotate(-p.wallSide*Math.min(3.5/60,Math.max(0,remaining)));if(remaining<=3.5/60+.00001)goal=null}let before=vy;step(1/60);if(before>0&&vy<0&&p){assert(!p.lethal);let q=mod(p.wallSide*(Math.PI/2-angle-p.start)),stops=Array.from({length:p.lines},(_,j)=>2.69+j*2.5/(p.lines-1));stops.push(TAU);goal=stops.find(t=>t>q+.04)??null}if(frameCount%30===0)draw()}
assert.equal(state,'won');assert.equal(passed,56);assert(completed[5]);assert(bestTimes[5]>0);assert(unlocked(6));nextLevel();assert.equal(level,6);assert.equal(platforms.length,50);`,box);
console.log('PASS: indigo section layout, fatal solid surfaces, continuous 25-floor drops, full-course playthrough and saved completion.');
// Rainbow finale: 50 floors, stronger spiral offsets, a solid finish, and a persistent celebration.
vm.runInContext(`assert.equal(level,6);assert.equal(platforms.length,50);assert.equal(finishPad.width,0);assert(finishPad.y>platforms[49].y);let turn=0;for(let i=1;i<50;i++){let d=mod(platforms[i].start-platforms[i-1].start);assert(d>.5);turn+=d}assert(Math.abs(turn-TAU*4)<1e-8);
let finaleTicks=0;while(state==='playing'&&finaleTicks++<20000){let p=platforms.find(p=>!p.broken);if(p){let d=Math.atan2(Math.sin(Math.PI/2-p.start-angle),Math.cos(Math.PI/2-p.start-angle));rotate(Math.max(-3.5/60,Math.min(3.5/60,d)))}step(1/60);if(finaleTicks%30===0)draw()}
assert.equal(state,'celebrate');assert.equal(passed,50);assert.equal(ballY,finishPad.y);assert.equal(vy,0);assert.equal($('#celebration').style.display,'block');assert.equal($('#overlay').style.display,'none');assert(completed.every(Boolean));assert(bestTimes[6]>0);assert($('#dots').innerHTML.includes('7 / 7 COLOURS'));let stillY=ballY,stillAngle=angle,stoppedTime=levelTime;left=true;for(let i=0;i<600;i++){step(1/60);if(i%30===0)draw()}assert.equal(ballY,stillY);assert.equal(angle,stillAngle);assert.equal(levelTime,stoppedTime);assert(fireworks.length>0&&fireworks.length<300);openPicker();let sparkCount=fireworks.length;step(1);assert.equal(fireworks.length,sparkCount);closePicker();assert.equal(state,'celebrate');selectLevel(0);assert.equal(state,'playing');assert.equal($('#celebration').style.display,'none');assert.equal(fireworks.length,0);assert.equal(finishPad,null);assert(completed.every(Boolean));`,box);
console.log('PASS: 50-floor four-turn finale, stable finish landing, fireworks, seven-colour completion, replay picker and cleanup.');
// Readiness uses real input handlers: a click alone does not begin a level.
const input={},readyEls=new Map();const readyBox={...box,localStorage:{},addEventListener(n,f){input[n]=f},document:{addEventListener(){},querySelector(s){if(!readyEls.has(s))readyEls.set(s,{style:{},setAttribute(){},setPointerCapture(){},addEventListener(n,f){input[n]=f},getContext(){return ctx}});return readyEls.get(s)}}};vm.createContext(readyBox);vm.runInContext(code,readyBox);
for(let course=0;course<7;course++){
vm.runInContext(`level=${course};restartLevel();letWaitY=ballY;for(let i=0;i<60;i++)update(1/60);assert(waitingForMove);assert.equal(ballY,letWaitY);assert.equal(vy,0);assert.equal(levelTime,0);rotate(0);assert(waitingForMove);`,readyBox);
input.pointerdown({pointerId:1,clientX:100,preventDefault(){}});input.pointermove({pointerId:1,clientX:100});input.pointerup({pointerId:1});
vm.runInContext('update(.1);assert(waitingForMove);assert.equal(levelTime,0);',readyBox);
input.keydown({code:'ArrowLeft',preventDefault(){}});vm.runInContext('update(1/60);assert(!waitingForMove);assert(ballY>letWaitY);assert(levelTime>0);restartLevel();',readyBox);
input.pointerdown({pointerId:2,clientX:100,preventDefault(){}});input.pointermove({pointerId:2,clientX:115});input.pointerup({pointerId:2});vm.runInContext('assert(!waitingForMove);update(1/60);assert(levelTime>0);',readyBox);
}
vm.runInContext("level=1;die();update(1);assert(waitingForMove);assert.equal(levelTime,0);level=0;finish();nextLevel();assert.equal(level,1);assert(waitingForMove);openPicker();closePicker();assert(waitingForMove);selectLevel(0);assert(waitingForMove);",readyBox);
console.log('PASS: all seven levels wait for drag/rotation keys, clicks stay idle, timers wait, and retry/next/picker reset readiness.');
// Endless streams beyond all milestones, retains bounded geometry, and never completes a main level.
vm.runInContext(`{startEndless();let mainBefore=JSON.stringify({completed,bestTimes});assert(endless);assert.equal(finishPad,null);assert(waitingForMove);let firstLayout=platforms.map(p=>p.start).join();startEndless();assert.notEqual(platforms.map(p=>p.start).join(),firstLayout);let ticksEndless=0;while(passed<250&&ticksEndless++<30000){let p=platforms.find(p=>!p.broken);angle=mod(Math.PI/2-p.start);step(1/60);if(ticksEndless%60===0)draw();assert.equal(state,'playing');assert(platforms.length<32)}assert(passed>=250);assert.equal(endlessBest,passed);assert.equal(JSON.stringify({completed,bestTimes}),mainBefore);openAchievements();let frozen=ballY,elapsed=levelTime;step(1);assert.equal(ballY,frozen);assert.equal(levelTime,elapsed);assert.equal(($('#ach-list').innerHTML.match(/UNLOCKED/g)||[]).length,5);closeAchievements();assert.equal(state,'playing');let score=passed,p=platforms.find(p=>!p.broken);p.hazard=.38;p.lines=0;p.lethal=false;p.tip=null;angle=mod(Math.PI/2-p.start-p.width/2-p.hazard/2);ballY=p.y-1;vy=100;step(.02);assert.equal(state,'ended');step(2);assert.equal(passed,score);assert.equal(endlessBest,score);assert.equal(JSON.stringify({completed,bestTimes}),mainBefore);$('#retry-endless').onclick();assert.equal(passed,0);assert(waitingForMove);assert.equal(endlessBest,score);selectLevel(0);assert(!endless);assert.equal(platforms.length,40);}`,box);
const endlessReload={...box,localStorage:{...box.localStorage}};vm.createContext(endlessReload);vm.runInContext(code,endlessReload);vm.runInContext(`assert(endlessBest>=250);openAchievements();assert($('#ach-summary').textContent.includes('7 / 7'));assert.equal(($('#ach-list').innerHTML.match(/UNLOCKED/g)||[]).length,5);`,endlessReload);
vm.runInContext(`completed=Array(7).fill(false);endlessBest=9;openAchievements();assert.equal(($('#ach-list').innerHTML.match(/UNLOCKED/g)||[]).length,0);closeAchievements();completed[0]=true;endlessBest=10;openAchievements();assert.equal(($('#ach-list').innerHTML.match(/UNLOCKED/g)||[]).length,1);assert($('#ach-list').innerHTML.includes('1 / 7'));closeAchievements();`,freshBox);
console.log('PASS: random endless generation, 250-platform run, bounded platforms, separate persistent record, death/retry, achievement thresholds and pause/resume.');


// Every shuffled cycle contains all seven approaches, with safe section entries and stable random colours.
vm.runInContext(`{startEndless();let seen=new Set(),palette=new Set(),sections=[];for(let n=0;n<140;n++){let p=platforms.find(p=>!p.broken);seen.add(p.style);palette.add(p.hue);assert(hues.includes(p.hue));let paint=colour(platforms.indexOf(p));time+=1;assert.equal(colour(platforms.indexOf(p)),paint);if(n%10===0){sections.push(p.style);assert(!p.hazard&&!p.lines&&p.wall===null&&!p.lethal)}if(n%10){if(p.style===1)assert(p.hazard>0);if(p.style===2)assert(p.hazard>0);if(p.style===3)assert(p.wall!==null);if(p.style===4)assert(p.lines>=3&&p.wall!==null);if(p.style===5&&n%10>=3)assert(p.lethal);if(p.style===6)assert.equal(p.width,1.05)}for(let k=0;k<p.splits;k++){angle=mod(Math.PI/2-p.start-k*TAU/p.splits);assert(gap(p)&&!danger(p))}p.broken=true;passed++;ballY=p.y+6;platforms=platforms.filter(p=>!p.broken);extendEndless();updateHUD();draw()}assert.equal(seen.size,7);assert(palette.size>1);assert.equal(new Set(sections.slice(0,7)).size,7);assert.equal(new Set(sections.slice(7)).size,7);for(let i=1;i<sections.length;i++)assert.notEqual(sections[i],sections[i-1]);}`,box);
console.log('PASS: seven shuffled endless styles, safe entries, usable gaps, random stable rainbow hues and section HUD.');
vm.runInContext(`{startEndless();assert(sound);rotate(.01);update(.1);let y=ballY,t=levelTime;openMenu();update(.5);assert.equal(state,'menu');assert.equal(ballY,y);assert.equal(levelTime,t);$('#sound').onclick();assert(!sound);closeMenu();assert.equal(state,'playing');openMenu();$('#achievements').onclick();assert.equal(state,'achievements');closeAchievements();assert.equal(state,'playing');openMenu();$('#levels').onclick();assert.equal(state,'picker');closePicker();assert.equal(state,'playing');openMenu();$('#restart').onclick();assert.equal(state,'playing');assert(waitingForMove);assert(!sound);start();assert(!sound);$('#sound').onclick();assert(sound);}`,readyBox);
console.log('PASS: menu pause/resume, navigation, restart and default sound with mute retained across modes.');

// Cut-edge walls must face the camera; back-facing walls would overpaint the platform top.
const edgeBox={...box,localStorage:{}};vm.createContext(edgeBox);vm.runInContext(code,edgeBox);
vm.runInContext(`{let path=[],faces=[],old={};for(let key of ['beginPath','moveTo','lineTo','fill'])old[key]=ctx[key];ctx.beginPath=()=>path=[];ctx.moveTo=ctx.lineTo=(x,y)=>path.push([x,y]);ctx.fill=()=>faces.push(path.slice());let p={y:0,start:0,splits:1,width:1.15,hazard:0,lines:0,wall:null};for(let k=0;k<360;k++){angle=k*TAU/360;faces=[];ring(p,0,false);ring(p,0,true);let edges=faces.filter(v=>v.length===4&&Math.abs(v[0][0]**2+((v[0][1]+camera)/.31)**2-65**2)<1e-5&&Math.abs(v[2][0]-v[1][0])<1e-8&&Math.abs(v[3][0]-v[0][0])<1e-8&&Math.abs(v[2][1]-v[1][1]-25)<1e-8&&Math.abs(v[3][1]-v[0][1]-25)<1e-8&&Math.abs(v[1][0]**2+((v[1][1]+camera)/.31)**2-151**2)<1e-5);let [a,b]=spans(p)[0];assert.equal(edges.length,Number(Math.cos(a+angle)<-1e-8)+Number(Math.cos(b+angle)>1e-8))}Object.assign(ctx,old);}`,edgeBox);
console.log('PASS: platform cut-edge visibility through a full 360-degree rotation.');

vm.runInContext(`{assert.equal(rotateSpeed,1);for(let speed of [.25,.55,1,1.35,2.75,3]){endless=false;level=0;restartLevel();$('#speed').value=speed;$('#speed').oninput();left=true;update(.01);assert(Math.abs(angle-.035*speed)<1e-8);assert.equal(Number(localStorage.prismSpeed),speed);assert.equal($('#speed-value').textContent,speed+'×')}restartLevel();}`,readyBox);
for(let speed of [.25,1.35,3]){vm.runInContext(`rotateSpeed=${speed};restartLevel();`,readyBox);input.pointerdown({pointerId:8,clientX:100,preventDefault(){}});input.pointermove({pointerId:8,clientX:110});input.pointerup({pointerId:8});vm.runInContext(`assert(Math.abs(angle-mod(-.2/scale*${speed}))<1e-8)`,readyBox)}
const speedBox={...box,localStorage:{prismSpeed:'1.5'}};vm.createContext(speedBox);vm.runInContext(code,speedBox);vm.runInContext('assert.equal(rotateSpeed,1.5)',speedBox);
console.log('PASS: default rotation speed, slower/faster keyboard and drag input, slider label and saved setting.');

readyBox.confirm=()=>false;
vm.runInContext(`{completed.fill(true);bestTimes.fill(12);endlessBest=250;saveProgress();startEndless();openMenu();let saved=localStorage.prismProgressV1;$('#clear-records').onclick();assert.equal(localStorage.prismProgressV1,saved);assert.equal(state,'menu');}`,readyBox);
readyBox.confirm=()=>true;
vm.runInContext(`{let speed=rotateSpeed,flip=direction,mute=sound;$('#clear-records').onclick();assert(completed.every(v=>!v));assert(bestTimes.every(v=>v===null));assert.equal(endlessBest,0);assert.equal(level,0);assert(!endless);assert(waitingForMove);assert.equal(state,'playing');assert(!unlocked(1));assert.equal(rotateSpeed,speed);assert.equal(direction,flip);assert.equal(sound,mute);let saved=JSON.parse(localStorage.prismProgressV1);assert.equal(saved.endlessBest,0);assert(saved.completed.every(v=>!v));openAchievements();assert(!$('#ach-list').innerHTML.includes('UNLOCKED'));closeAchievements();}`,readyBox);
console.log('PASS: clear-records cancellation, confirmed reset, saved progress reset, safe fresh run and preserved settings.');
vm.runInContext(`{let random=Math.random;try{for(let chance of [.29,.3,.9]){endless=false;level=0;restartLevel();Math.random=()=>chance;angle=Math.PI/2;waitingForMove=false;ballY=-1;vy=420;update(.02);assert.equal(passed,1);assert.equal(fireworks.length,chance<.3?48:0);if(fireworks.length){openMenu();let life=fireworks[0].life;update(.5);assert.equal(fireworks[0].life,life);closeMenu();ballY=-100;vy=0;update(.02);assert(fireworks[0].life<life);celebrate(3,false);assert.equal(fireworks.length,0)}}}finally{Math.random=random}}`,readyBox);
console.log('PASS: chance-based platform fireworks, menu pause, animation and particle cleanup.');

